version: '3.6'

services:

  # Front End
  sonos-front-end:
    container_name: sonos-front_end
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    command: npm run serve
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - sonos-net

networks:
  sonos-net:
    external:
      name: backend_network
